### ISSUE TITLE
[Add]: George Design System

### ISSUE THREAD

**Issue by konki-vienna** [Design-System-Cookbooks/design-systems#8]
### Company Name

George-Labs GmbH

### Company Logo

https://george-labs.com/wp-content/uploads/2019/06/GL-Logo-B.png

### System Name (if applicable)

George Design System

### Devices the Company is Targeting (e.g., Web, iOS, Android)

Web, iOS, Android

### Code Documentation URL (if available)

https://designsystem.george-labs.com/

### Voice & Tone Page URL (if available)

https://designsystem.george-labs.com/main/guides/content/introduction/

### Design Tokens Used (Yes/No)

Yes

### Storybook Link (if available)

https://designsystem.george-labs.com/storybook/?path=/story/about-changelog--page

### Multi-Brand Design System (Yes/No)

No

**Comment by konsalex** [comment]
Thanks @konki-vienna just added it! 🚀
